import { useState } from "react"
import { ChevronDown, ChevronRight, Trash2 } from "lucide-react"
import type { Category, Module } from "@/types/quiz"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface Props { modules: Module[]; categories: Category[]; selectedModuleIds: string[]; onAddCategory: (name: string) => void; onDeleteCategory: (id: string) => void; onToggleModule: (id: string) => void; onToggleAllInCategory: (id: string) => void; onToggleCategoryExpand: (id: string) => void; onDeleteModule: (id: string) => void }
export function CategoryManager(props: Props) { const [name, setName] = useState(''); const groups = [...props.categories.map(c => ({ ...c, modules: props.modules.filter(m => m.categoryId === c.id) })), { id: '__uncategorized__', name: 'Uncategorized', isExpanded: true, moduleIds: [], modules: props.modules.filter(m => !m.categoryId && !props.categories.some(c => c.moduleIds.includes(m.id))) }]; return <div className="space-y-4"><div className="flex gap-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder="New category name" onKeyDown={e => { if (e.key === 'Enter' && name.trim()) { props.onAddCategory(name.trim()); setName('') } }} /><Button onClick={() => { if (name.trim()) { props.onAddCategory(name.trim()); setName('') } }}>Add</Button></div>{groups.map(group => <Card key={group.id}><CardHeader className="flex-row items-center justify-between py-3"><Button variant="ghost" onClick={() => group.id !== '__uncategorized__' && props.onToggleCategoryExpand(group.id)}>{group.isExpanded ? <ChevronDown /> : <ChevronRight />}{group.name}</Button>{group.id !== '__uncategorized__' && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => props.onToggleAllInCategory(group.id)}>Toggle all</Button><Button size="icon-sm" variant="destructive" onClick={() => props.onDeleteCategory(group.id)} aria-label={`Delete ${group.name}`}><Trash2 /></Button></div>}</CardHeader>{group.isExpanded && <CardContent className="space-y-2">{group.modules.map(module => <div key={module.id} className="flex items-center gap-3 rounded-md border p-3"><Checkbox id={`category-module-${module.id}`} checked={props.selectedModuleIds.includes(module.id)} onCheckedChange={() => props.onToggleModule(module.id)} /><Label htmlFor={`category-module-${module.id}`} className="flex-1">{module.title}</Label><Button size="icon-sm" variant="ghost" onClick={() => props.onDeleteModule(module.id)} aria-label={`Delete ${module.title}`}><Trash2 /></Button></div>)}</CardContent>}</Card>)}</div> }
