import { ChevronDown, ChevronRight, Copy, RefreshCw, Share2, Trash2, Upload } from "lucide-react"
import type { Module } from "@/types/quiz"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

interface Props { modules: Module[]; selectedIds: string[]; expandedModules: Set<string>; collapsedCategories: Set<string>; onToggleModule: (id: string) => void; onToggleExpand: (id: string) => void; onDeleteModule: (id: string) => void; onToggleCollapse: (key: string) => void; onToggleSelectAll: (ids: string[], select: boolean) => void; onSharing: (module: Module) => void; onCopyLink: (module: Module) => void; onReplace: (module: Module) => void; onSync: (id: string) => void }
export function ModuleList(props: Props) {
  const categories = Array.from(new Set(props.modules.map(m => m.categoryId).filter(Boolean))).sort() as string[]
  const groups = [...categories.map(title => ({ title, key: title, modules: props.modules.filter(m => m.categoryId === title) })), { title: 'Uncategorized', key: '__uncategorized__', modules: props.modules.filter(m => !m.categoryId) }].filter(g => g.modules.length)
  return <div className="space-y-3">{groups.map(group => { const collapsed = props.collapsedCategories.has(group.key); const ids = group.modules.map(m => m.id); const all = ids.every(id => props.selectedIds.includes(id)); return <Card key={group.key}><CardHeader className="flex-row items-center justify-between gap-2 py-3"><Button variant="ghost" className="justify-start px-1 font-semibold" onClick={() => props.onToggleCollapse(group.key)} aria-expanded={!collapsed}>{collapsed ? <ChevronRight /> : <ChevronDown />}{group.title}</Button>{!collapsed && <Button size="sm" variant="outline" onClick={() => props.onToggleSelectAll(ids, !all)}>{all ? 'Deselect all' : 'Select all'}</Button>}</CardHeader>{!collapsed && <CardContent className="space-y-2">{group.modules.map(module => { const selected = props.selectedIds.includes(module.id); const expanded = props.expandedModules.has(module.id); return <div key={module.id} className={cn("flex flex-wrap items-start gap-3 rounded-md border p-3", selected && "border-primary bg-accent")}><Checkbox id={`module-${module.id}`} checked={selected} onCheckedChange={() => props.onToggleModule(module.id)} className="mt-1" /><div className="min-w-48 flex-1"><Label htmlFor={`module-${module.id}`} className="cursor-pointer font-medium">{module.title}</Label><p className="text-xs text-muted-foreground">v{module.currentVersion ?? 1}{module.subscribed ? module.frozen ? ' · frozen' : ' · live subscription' : module.visibility === 'live' ? ' · shared live' : ' · private'}</p>{module.description && <Button type="button" variant="link" className={cn("block h-auto w-full justify-start p-0 text-left text-sm font-normal text-muted-foreground", !expanded && "truncate")} onClick={() => props.onToggleExpand(module.id)} aria-expanded={expanded}>{module.description}</Button>}</div><div className="flex gap-1">{module.isOwner && <Button variant="ghost" size="icon-sm" onClick={() => props.onReplace(module)} aria-label={`Replace ${module.title}`}><Upload /></Button>}{module.isOwner && <Button variant="ghost" size="icon-sm" onClick={() => props.onSharing(module)} aria-label={`${module.visibility === 'live' ? 'Disable sharing for' : 'Share'} ${module.title}`}><Share2 /></Button>}{module.isOwner && module.visibility === 'live' && <Button variant="ghost" size="icon-sm" onClick={() => props.onCopyLink(module)} aria-label={`Copy link for ${module.title}`}><Copy /></Button>}{module.subscribed && !module.frozen && <Button variant="ghost" size="icon-sm" onClick={() => props.onSync(module.id)} aria-label={`Update ${module.title}`}><RefreshCw /></Button>}<Button variant="ghost" size="icon-sm" onClick={() => props.onDeleteModule(module.id)} aria-label={`Delete ${module.title}`}><Trash2 /></Button></div></div>})}</CardContent>}</Card> })}</div>
}
